services:
  kong:
    image: kong/kong-gateway:3.10.0.1
    container_name: hrm_kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      JWT_SECRET: ${JWT_SECRET:-"a-string-secret-at-least-256-bits-long"}
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002" # Added port for admin GUI
    volumes:
      - ./kong:/kong/declarative/
    networks:
      - shared_network

networks:
  shared_network:
    name: hrm_shared_network
    external: true
